### ISSUE TITLE
Does not work on stable anymore?

### ISSUE THREAD

**Issue by Jokler** [rust-shell-script/rust_cmd_lib#13]
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/jokler/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/cmd_lib_macros-0.1.0/src/lib.rs:1:1
  |
1 | #![feature(proc_macro_span)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `cmd_lib_macros`.

```

**Comment by gkourgkoutas** [comment]
I get the same error. Compiling with nightly works.

**Comment by rust-shell-script** [comment]
see #12 and https://github.com/rust-lang/rust/issues/54725.

**Comment by joseluis** [comment]
The latest version that works for me on stable is v8.4 from 25th aug if referencing the github commit directly like this: 
```
cmd_lib = {git = "https://github.com/rust-shell-script/rust_cmd_lib/", rev = "88eaa7988d27f517251be35fe8a7b21274d04837"}
```

Or version  0.7.8 when using crates.io:
`cmd_lib = "0.7.8"`

I don't know why versions `0.8.*` doesn't work through crates IO on stable.

**Comment by rust-shell-script** [comment]
Version 0.10 can be built with stable rust toolchain, and it also includes other improvements. Just let me know if it works for you.

**Comment by Jokler** [comment]
Seems to work fine for me now.
Thank you! :)

**Comment by rust-shell-script** [comment]
@hendrikmaus it looks like the errors were from proc-macro-error/structopt-derive/structopt.
