### ISSUE TITLE
How do I get the return code of the command?

### ISSUE THREAD

**Issue by NightMachinary** [rust-shell-script/rust_cmd_lib#15]
I tried this but it did not work:
```
    if run_fun!(rg --quiet -F "LayoutTU.S." $HOME/Library/Preferences/com.apple.HIToolbox.plist).is_err() {
        println!("🇮🇷" )
    } else {
        println!("🇺🇸" )
    }
```

**Comment by tao-guo** [comment]
$HOME is a sh/bash variable, and you can use [std::env::var](https://doc.rust-lang.org/std/env/fn.var.html) instead. For printing error messages from result, check https://doc.rust-lang.org/std/result/.

**Comment by NightMachinary** [comment]
> $HOME is a sh/bash variable, and you can use [std::env::var](https://doc.rust-lang.org/std/env/fn.var.html) instead. For printing error messages from result, check https://doc.rust-lang.org/std/result/.

I know, I have set HOME in a var before this code snippet. I do not want to get the error message; I just need the exit code.

**Comment by tao-guo** [comment]
You can try this: https://doc.rust-lang.org/std/io/struct.Error.html#method.raw_os_error
