### ISSUE TITLE
Iterate over options

### ISSUE THREAD

**Issue by akiradeveloper** [rust-shell-script/rust_cmd_lib#17]
Let's suppose we have a command named x and think about this code.

```rust
let options = vec!["-a -b 1", "-c 2"];
for option in options {
  run_cmd!(x $option).unwrap();
}
```

doesn't recognize each option correctly but handle as a atomic variable.

How can I do this with this library?

**Comment by rust-shell-script** [comment]
In that case, you don't need to use macros. You can just use run_cmd() function instead:
```
run_cmd("x {}", option).unwrap();
```

**Comment by akiradeveloper** [comment]
Thank you! It works!
