### ISSUE TITLE
Would the performance be the same with your library vs "std::process::Command"

### ISSUE THREAD

**Issue by Joe23232** [rust-shell-script/rust_cmd_lib#18]
```rust
Command::new("sh")
    .arg("-c")
    .arg("echo \"%{l}Hello%{c}yellow%{r}Bar\" | lemonbar -p -F#ffffff -B#232323")
    .spawn()
    .expect("Error: connect run \"lemonbar\" Please ensure it is installed!");
```

If I were to run this exact same command into your library, would the performance be the same or is it literally using `bash`?

**Comment by rust-shell-script** [comment]
This library does not need to launch an additional `bash` process to run the commands and there is also no runtime parsing/interpreting comparing to bash, so it is expected that the performance will be better. However, performance is not what the library is focusing on. If you really care about it, you should not call any external commands.

BTW, bash script's performance is notorious bad: http://spencertipping.com/posts/2013.0814.bash-is-irrecoverably-broken.html.

**Comment by Joe23232** [comment]
I see thanks mate.
