### ISSUE TITLE
Consider adding a link to Scriptisto as a tip

### ISSUE THREAD

**Issue by igor-petruk** [rust-shell-script/rust_cmd_lib#2]
FYI: https://github.com/igor-petruk/scriptisto. 

Written in Rust, but language-agnostic. Would work pretty cool with this library :)

**Comment by tao-guo** [comment]
rust_cmd_lib encourages AOT compilation, to avoid all kinds of issues as in normal shell scripts. Close it for now. Thanks for the recommendation.
