### ISSUE TITLE
Feature request: Allow cd-ing to a path

### ISSUE THREAD

**Issue by danielzfranklin** [rust-shell-script/rust_cmd_lib#24]
It would be convenient if this was valid

```rust
let dir = Path::from(...);
run_cmd! {
    cd $dir;
    rm foo;
}
```

the workaround is fine, but mildly less convenient

```rust
let dir = Path::from(...);
let dir_s = dir.to_string();
run_cmd! {
    cd $dir_s;
    rm foo;
}
```

**Comment by rust-shell-script** [comment]
Have you tried your own example? it seems not valid.
 Also you need to handle the string conversion failure case.

**Comment by danielzfranklin** [comment]
My apologies. It should have been `dir.to_str().unwrap();` I totally understand if you're not interested in implementing this. I might have time to give it a shot. Is this something you'd be willing to accept a PR doing?

**Comment by rust-shell-script** [comment]
Yes, of course, all PRs are welcome. It might be not that easy, since proc macros are already calling `to_string()` for all the variables. However, you may still be able to do some special things for "cd xxx" command?
TBH all the `current_dir` in the source code should be `AsRef<Path>` ...
