### ISSUE TITLE
spawn: doesn't appear as though file descriptors are inherited

### ISSUE THREAD

**Issue by da-x** [rust-shell-script/rust_cmd_lib#30]
I tried a long running command, e.g:

```
spawn!(docker build -f ${tmp_docker_file} -t ${tag} ${tmp_path_sub})?.wait_cmd_result()?;
```

But output blocked until the command finished execution successfully.
Parent command executed in a terminal. 

Consistently, I don't see `Stdio::inherit()` being used the code of `rust_cmd_lib`.

The alternative to use the standard API worked for me:

```
use std::process::{Stdio, Command};   
let mut cmd = Command::new("docker"); 
cmd.stdout(Stdio::inherit());         
cmd.stderr(Stdio::inherit());         
cmd.stdin(Stdio::inherit());          
cmd.arg("build");                     
cmd.arg("-f");                        
cmd.arg(tmp_docker_file);             
cmd.arg("-t");                        
cmd.arg(tag);                         
cmd.arg(tmp_path_sub);                
let mut child = cmd.spawn()?;         
child.wait()?;
```

**Comment by rust-shell-script** [comment]
Thanks for reporting this, just fixed in the last commit.

BTW, Stdio::inherit() is the default setting, so we don't need to call it explicitly. I would also just use run_cmd!() for your above example.

**Comment by da-x** [comment]
Thanks! I reviewed the changes and added a few comments.
