### ISSUE TITLE
Stderr is unconditionally redirected

### ISSUE THREAD

**Issue by andylizi** [rust-shell-script/rust_cmd_lib#34]
### Description

Contents of stderr will always be sliently redirected and consumed.

### Reproduction

`cargo build` outputs are printed to stderr, so we can use it as a demo:

```rust
run_cmd!(cargo build).unwrap();
```

Run it and nothing happens.

### The Cause

In bd7837f5f1598ada36826391ae10db93215e83be, an attempt to fix logging for stderr:

https://github.com/rust-shell-script/rust_cmd_lib/blob/f125db860a67050f6f0c4d2c4b160ef32f8f0af2/src/process.rs#L464-L467

**Comment by rust-shell-script** [comment]
It is intentional. You need to set up a logger to show it. See readme.
