### ISSUE TITLE
Command never ends when being executed in cmd_lib::spawn_with_output

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [rust-shell-script/rust_cmd_lib#35]
I have a ffmpeg command to process a video file.

`ffmpeg -i 4.mp4 -i a2.png -ss 00:00:00 -to 00:01:00 -y -filter_complex "overlay=x=263:y=752"  -c:a copy -max_muxing_queue_size 9999 -nostdin testtttt.mp4`

It runs very well when being executed in a terminal. But when I run it with `cmd_lib::spawn_with_output`, it never ends and the program just stuck there. This is my program.
```rust
fn main() -> eyre::Result<()>{
    std::env::set_current_dir(r##"f:\temp"##);

    println!("{:?}", "Starting......");
    let output = cmd_lib::spawn_with_output!(
ffmpeg -i 4.mp4 -i a2.png -ss 00:00:00 -to 00:01:00 -y -filter_complex "overlay=x=263:y=752"  -c:a copy -max_muxing_queue_size 9999 -nostdin testtttt.mp4
    )?.wait_fun_result()?;
    println!("{:?}", "Done!");
    println!("{:?}", output);
    println!("{:?}", output.trim());
    Ok(())
}
```
Is there something I'm doing wrong? Thanks.

**Comment by rust-shell-script** [comment]
Seems like the same issue as this one: https://stackoverflow.com/questions/34611742/how-do-i-read-the-output-of-a-child-process-without-blocking-in-rust. If the final output is larger than default kernel pipe size, it will block.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the link. I've read it but still now sure how to handle the issue. Do you have any suggestions?

**Comment by tao-guo** [comment]
Yes, the fix should be in cmd_lib. After adding logging support, the generated code will a little different than your above code. I just made some changes, you can check if it fixes your problem. thanks.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Yes, the fix should be in cmd_lib. After adding logging support, the generated code will a little different than your above code. I just made some changes, you can check if it fixes your problem. thanks.

Thanks, it works now. Sorry for the late response. I can't find the issues tab the other day.
