### ISSUE TITLE
Consider adding a "quiet()" method.

### ISSUE THREAD

**Issue by VentGrey** [rust-shell-script/rust_cmd_lib#4]
This is to prevent filling the screen with a lot of text.

**Comment by yxdunc** [comment]
Some logs are removed on master (not pushed to crates.io yet).
A better solution is to implement a proper logger, @tao-guo suggested that he might work on it at some point. 😊

cf https://github.com/rust-shell-script/rust_cmd_lib/pull/3

**Comment by casidiablo** [comment]
:+1: i would love to disable logs completely.
