### ISSUE TITLE
Problem with pipefail

### ISSUE THREAD

**Issue by manfredlotz** [rust-shell-script/rust_cmd_lib#48]
I have this minimal example

```
fn main() -> CmdResult {
    cmd_lib::set_pipefail(true);
    println!("{}", run_fun!(du -ah . | sort -hr | head -n 10)?);
    Ok(())
}
```

and get

```
Error: Custom { kind: Other, error: "Running [\"sort\", \"-hr\"] exited with error; terminated by signal: 13" }
```

Running `du -ah . | sort -hr | head -n 10` in the shell no matter if bash/zsh or fish, works (no suprise) fine.

**Comment by rust-shell-script** [comment]
This library gives sh's `set -euo pipefail` settings by default. 
Close it for now since you already know how to set the pipefail behavior.

**Comment by manfredlotz** [comment]
It seems I wasn't clear when I opened this issue.

This sequence `du -ah . | sort -hr | head -n 10` doesn't produce an error as there is no error.

Why does it produce an error when `cmd_lib::set_pipefail(true);` is issued?

**Comment by rust-shell-script** [comment]
```
➜  rust_cmd_lib git:(master) ✗ cat test.sh 
#!/bin/bash

set -o pipefail

du -ah . | sort -hr | head -n 10
ret=$?
echo "ret=$ret"

➜  rust_cmd_lib git:(master) ✗ ./test.sh  
586M	.
568M	./target/debug
568M	./target
219M	./target/debug/deps
218M	./target/debug/incremental
81M	./target/debug/examples
48M	./target/debug/build
24M	./target/debug/deps/libstructopt_derive-2eca5f976c187cb9.so
23M	./target/debug/examples/dd_test
23M	./target/debug/deps/libsyn-c102b3a26df52884.rlib
ret=141
```
Because the pipe has been closed, so you will get a EPIPE error if the pipefail option has been enabled. 
FYI: https://blog.cloudflare.com/pipefail-how-a-missing-shell-option-slowed-cloudflare-down/

**Comment by manfredlotz** [comment]
Thanks I didn't know about this bash bug.
