### ISSUE TITLE
Prevent stripping quotes?

### ISSUE THREAD

**Issue by chrisalcantara** [rust-shell-script/rust_cmd_lib#5]
Is there a way to keep quotes intact when passing a series of commands to
`run_cmd!`?

I'm trying to do the following:

```
let msg: &str = "update the repository";
let _ = run_cmd!("git commit -am \"{}\"; git push origin master", msg);
```

Here I'd like to keep the `msg` within quotes when passed to the `git commit`
command, but `run_cmd` strips the quotes. Any guidance on this would be appreciated.

**Comment by tao-guo** [comment]
hmm, it should work. What about using below code ?
```
let msg: &str = "\"update the repository\"";
```
The final interface for this needs some clean up.

**Comment by chrisalcantara** [comment]
That worked. Thanks for talking it out!

**Comment by rust-shell-script** [comment]
update: now you can run command like this:

let msg: &str = "update the repository";
let _ = run_cmd!(|msg| git commit -am "$msg"; git push origin master);
