### ISSUE TITLE
Command substitution workaround

### ISSUE THREAD

**Issue by shafouz** [rust-shell-script/rust_cmd_lib#53]
Hi, i couldn't use <(cmd) is there any other workaround without doing something like:

```bash
cmd > tempfile
cmd2 tempfile
rm tempfile
```

**Comment by rust-shell-script** [comment]
This library is deliberately not supporting something like this. As the `cmd` could fail, it could introduce silent failures and other bash pitfalls.

Close it as wontfix, and you can always run your command with `bash -c "..."` if you really want some fancy bash features.

**Comment by shafouz** [comment]
i see ty
