### ISSUE TITLE
Strange behavior with current_dir().

### ISSUE THREAD

**Issue by virtualritz** [rust-shell-script/rust_cmd_lib#6]
I'm trying to extract some payload from a macOS package in a `build.rs`.
This is located in `./target/3Delight/3delight.pkg`.
So if I do this in my shell:
```Shell
cd target/3Delight/3delight.pkg; cat Payload | gunzip -dc | cpio -i
```
I end up with the Payload unpacked in `./target/3Delight/3delight.pkg`.

But if I run below Rust code, my Payload is unpacked in `.`, not in `./target/3Delight/3delight.pkg`.

I do not understand this. `cat Payload` will only work from `./target/3Delight/3delight.pkg`. How is it possible that the output ends up three levels above?

```Rust
Process::new("cat Payload")
    .pipe("gunzip -dc")
    .pipe("cpio -i")
    .current_dir(extract_path.to_str().unwrap())
    .wait::<CmdResult>().expect("Could no extract payload from package.");
```

Output:
```shell
INFO: Running "cat Payload | gunzip -dc | cpio -i (cd: /Users/moritz/code/bindit/target/3Delight/3delight.pkg)"
```

**Comment by rust-shell-script** [comment]
This might be due to macos's special pipe command mechanism.  I have updated the code, could you try your commands again? thx
