### ISSUE TITLE
Regression >=0.10: Behavior with empty string

### ISSUE THREAD

**Issue by akiradeveloper** [rust-shell-script/rust_cmd_lib#63]
This code panics with "No such file or directory" with version 0.10 or above.

```rust
use cmd_lib::*;
fn main() {
    dbg!(run_cmd!(ls));
    let options = "";
    dbg!(run_cmd!(ls $options));
}
```

I think `ls ""` should be interpreted as `ls` in this library. 

Is this your intention? and is there some workaround?

**Comment by rust-shell-script** [comment]
Thanks for reporting this. Yeah, it is better to skip the empty arguments.
