### ISSUE TITLE
同步执行命令?

### ISSUE THREAD

**Issue by lionoggo** [rust-shell-script/rust_cmd_lib#8]
使用run_cmd进入指定工作目录下执行gradle命令,期待.gradlew命令执行结束后下述方法才返回.但我发现首先输出build  failed错误日志,然后才./gradlew :assembleDebug才开始执行.有什么方式能同步执行?
example:
    if run_cmd! {
        cd /Users/person/app;
        ./gradlew :assembleDebug
    }
    .is_err()
    {
        eprintln!("build  failed");
    }

**Comment by rust-shell-script** [comment]
It has nothing to do with synchronous execution, but stderr will always do unbuffered print and the messages can appear earlier than stdout print. You can call `io::stdout().flush().unwrap()` to flush stdout buffer before reporting errors to stderr.
